/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import excepciones.JuegoExcepcion;
import excepciones.PilaExcepcion;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import juego.ClsJuego;
import pilas.Nodo;
import sun.swing.table.DefaultTableCellHeaderRenderer;

/**
 *
 * @author luis arguello
 */
public class InterfazHanoi extends javax.swing.JFrame {

    DefaultTableModel modeloTablaTorre1, modeloTablaTorre2, modeloTablaTorre3;
    ClsJuego juego = new ClsJuego();
    int numDiscos;

    public InterfazHanoi() {
        initComponents();

        modeloTablaTorre1 = (DefaultTableModel) tb_Torre1.getModel();
        modeloTablaTorre1.setRowCount(10);

        modeloTablaTorre2 = (DefaultTableModel) tb_Torre2.getModel();
        modeloTablaTorre2.setRowCount(10);

        modeloTablaTorre3 = (DefaultTableModel) tb_Torre3.getModel();
        modeloTablaTorre3.setRowCount(10);

        DefaultTableCellRenderer renderTorre1 = new DefaultTableCellHeaderRenderer();
        renderTorre1.setHorizontalAlignment(SwingConstants.CENTER);
        tb_Torre1.getColumnModel().getColumn(0).setCellRenderer(renderTorre1);

        DefaultTableCellRenderer renderTorre2 = new DefaultTableCellHeaderRenderer();
        renderTorre2.setHorizontalAlignment(SwingConstants.CENTER);
        tb_Torre2.getColumnModel().getColumn(0).setCellRenderer(renderTorre2);

        DefaultTableCellRenderer renderTorre3 = new DefaultTableCellHeaderRenderer();
        renderTorre3.setHorizontalAlignment(SwingConstants.CENTER);
        tb_Torre3.getColumnModel().getColumn(0).setCellRenderer(renderTorre3);

    }

    private void presentarTorre1() {
        ((DefaultTableModel) tb_Torre1.getModel()).setRowCount(0);
        modeloTablaTorre1.setRowCount(10);
        Nodo nodo;
        String[] vector;
        int filaDisco = (10 - juego.obtenerPila(1).size());
        if (juego.obtenerPila(1).size() > 0) {
            for(int i = 0;i<juego.obtenerPila(1).size();i++){
                vector = juego.obtenerPila(1).imprimirPila();
                modeloTablaTorre1.insertRow(filaDisco, vector);
                filaDisco++;
            }
            
        }
        
        tb_Torre1.setModel(modeloTablaTorre1);
        modeloTablaTorre1.setRowCount(10);
        
        
        //System.out.println();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tb_Torre2 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tb_Torre1 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        tb_Torre3 = new javax.swing.JTable();
        btn_1_B = new javax.swing.JButton();
        btn_1_C = new javax.swing.JButton();
        btn_2_A = new javax.swing.JButton();
        btn_2_C = new javax.swing.JButton();
        btn_3_A = new javax.swing.JButton();
        btn_3_B = new javax.swing.JButton();
        cb_NumDiscos = new javax.swing.JComboBox<>();
        lbl_MinMovimientos = new javax.swing.JLabel();
        lbl_Movimientos = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btn_Reiniciar = new javax.swing.JButton();
        btn_Resolver = new javax.swing.JButton();
        btn_Iniciar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tb_Torre2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Torre 2"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb_Torre2.setAutoscrolls(false);
        tb_Torre2.setFocusable(false);
        tb_Torre2.setRowSelectionAllowed(false);
        tb_Torre2.setShowHorizontalLines(false);
        tb_Torre2.setShowVerticalLines(false);
        jScrollPane2.setViewportView(tb_Torre2);
        if (tb_Torre2.getColumnModel().getColumnCount() > 0) {
            tb_Torre2.getColumnModel().getColumn(0).setResizable(false);
        }

        tb_Torre1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Torre 1"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb_Torre1.setAutoscrolls(false);
        tb_Torre1.setFocusable(false);
        tb_Torre1.setRowSelectionAllowed(false);
        tb_Torre1.setShowHorizontalLines(false);
        tb_Torre1.setShowVerticalLines(false);
        jScrollPane3.setViewportView(tb_Torre1);
        if (tb_Torre1.getColumnModel().getColumnCount() > 0) {
            tb_Torre1.getColumnModel().getColumn(0).setResizable(false);
        }

        tb_Torre3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Torre 3"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb_Torre3.setAutoscrolls(false);
        tb_Torre3.setFocusable(false);
        tb_Torre3.setRowSelectionAllowed(false);
        tb_Torre3.setShowHorizontalLines(false);
        tb_Torre3.setShowVerticalLines(false);
        jScrollPane4.setViewportView(tb_Torre3);
        if (tb_Torre3.getColumnModel().getColumnCount() > 0) {
            tb_Torre3.getColumnModel().getColumn(0).setResizable(false);
        }

        btn_1_B.setText("B");

        btn_1_C.setText("C");

        btn_2_A.setText("A");

        btn_2_C.setText("C");

        btn_3_A.setText("A");
        btn_3_A.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_3_AActionPerformed(evt);
            }
        });

        btn_3_B.setText("B");

        cb_NumDiscos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "3", "4", "5", "6", "7", "8", "9", "10" }));
        cb_NumDiscos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_NumDiscosActionPerformed(evt);
            }
        });

        lbl_MinMovimientos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_MinMovimientos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbl_Movimientos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Movimientos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel3.setText("Numero Discos");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel4.setText("Numero Movimientos");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel5.setText("Numero Minimo Movimientos");

        btn_Reiniciar.setText("Reiniciar");

        btn_Resolver.setText("Resolver");
        btn_Resolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ResolverActionPerformed(evt);
            }
        });

        btn_Iniciar.setText("Iniciar");
        btn_Iniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_IniciarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(33, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(btn_1_C)
                        .addGap(81, 81, 81)
                        .addComponent(btn_2_A)
                        .addGap(37, 37, 37)
                        .addComponent(btn_2_C)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_3_A)
                        .addGap(37, 37, 37)
                        .addComponent(btn_3_B)
                        .addGap(50, 50, 50))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cb_NumDiscos, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(37, 37, 37)
                                .addComponent(lbl_MinMovimientos, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(29, 29, 29)
                                        .addComponent(btn_Iniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_Movimientos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_Reiniciar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_Resolver, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63))))
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_1_B)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_1_B)
                    .addComponent(btn_1_C)
                    .addComponent(btn_2_A)
                    .addComponent(btn_2_C)
                    .addComponent(btn_3_A)
                    .addComponent(btn_3_B))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_NumDiscos, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_MinMovimientos, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_Movimientos, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Iniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Reiniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Resolver, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cb_NumDiscosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_NumDiscosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_NumDiscosActionPerformed

    private void btn_3_AActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_3_AActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_3_AActionPerformed

    private void btn_ResolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ResolverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_ResolverActionPerformed

    private void btn_IniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_IniciarActionPerformed
        try {
            // TODO add your handling code here:
            juego.iniciarJuego(Integer.parseInt(cb_NumDiscos.getSelectedItem().toString()));
            this.presentarTorre1();

        } catch (JuegoExcepcion ex) {
            Logger.getLogger(InterfazHanoi.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_IniciarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazHanoi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazHanoi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazHanoi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazHanoi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new InterfazHanoi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_1_B;
    private javax.swing.JButton btn_1_C;
    private javax.swing.JButton btn_2_A;
    private javax.swing.JButton btn_2_C;
    private javax.swing.JButton btn_3_A;
    private javax.swing.JButton btn_3_B;
    private javax.swing.JButton btn_Iniciar;
    private javax.swing.JButton btn_Reiniciar;
    private javax.swing.JButton btn_Resolver;
    private javax.swing.JComboBox<String> cb_NumDiscos;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lbl_MinMovimientos;
    private javax.swing.JLabel lbl_Movimientos;
    private javax.swing.JTable tb_Torre1;
    private javax.swing.JTable tb_Torre2;
    private javax.swing.JTable tb_Torre3;
    // End of variables declaration//GEN-END:variables
}
